import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import AppDatePickerProvider from "./Components/Features/AppDatePicker";
import WhatsAppIcon from "./Components/WhatsappIcon";
import Head from "next/head";


export const metadata = {
  title: "D Square Events Center",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      </head>
      <body
        className=""
      >
        <Navbar />
    
        <AppDatePickerProvider>{children}</AppDatePickerProvider>

        <WhatsAppIcon />
       
        <Footer />


      </body>
    </html>
  );
}
