import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import AppDatePickerProvider from "./Components/Features/AppDatePicker";
import WhatsAppIcon from "./Components/WhatsappIcon";


export const metadata = {
  title: "D Square Events Center",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className=""
      >
        <Navbar />
    
        <AppDatePickerProvider>{children}</AppDatePickerProvider>

        <WhatsAppIcon />
       
        <Footer />


      </body>
    </html>
  );
}
